services:
  web:
    build: .
    image: varungupta2809/earthquake-damage-assessment:latest
    container_name: earthquake-app
    ports:
      - "5000:5000"
    environment:
      - SECRET_KEY=${SECRET_KEY:-supersecretkey123}
      - DB_USER=${DB_USER:-root}
      - DB_PASSWORD=${DB_PASSWORD:-password}
      - DB_HOST=${DB_HOST:-db}
      - DB_PORT=${DB_PORT:-3306}
      - DB_NAME=${DB_NAME:-earthquake_db}
      - ALGORITHM=${ALGORITHM:-HS256}
      - ACCESS_TOKEN_EXPIRE_MINUTES=${ACCESS_TOKEN_EXPIRE_MINUTES:-60}
    volumes:
      - ./app/static/upload_image:/app/app/static/upload_image
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - earthquake-network

  db:
    image: mysql:8.0
    container_name: earthquake-db
    environment:
      - MYSQL_ROOT_PASSWORD=${DB_PASSWORD:-password}
      - MYSQL_DATABASE=${DB_NAME:-earthquake_db}
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${DB_PASSWORD:-password}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    restart: unless-stopped
    networks:
      - earthquake-network

volumes:
  mysql-data:
    driver: local

networks:
  earthquake-network:
    driver: bridge

